language: ruby

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd spec/dummy
  - cp config/database.travis.yml config/database.yml
  - bundle install
  - bundle exec rake db:create db:migrate
  - cd ../../

rvm:
  - 2.0.0
  - 2.1

script: bundle exec rspec spec
